-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:cca22c7a44d636ca0d6a18d9c5eae399$
-- 

return {
	texture = 'main.png',
	frames = {
			{
				name = "220px-Lenna.png",
				spriteColorRect = { x = 0, y = 0, width = 220, height = 220 },
				uvRect = { u0 = 0.0078125, v0 = 0.00390625, u1 = 0.867188, v1 = 0.433594 },
				spriteSourceSize = { width = 220, height = 220 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite1.png",
				spriteColorRect = { x = 0, y = 0, width = 120, height = 120 },
				uvRect = { u0 = 0.484375, v0 = 0.675781, u1 = 0.953125, v1 = 0.910156 },
				spriteSourceSize = { width = 120, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite2.png",
				spriteColorRect = { x = 0, y = 0, width = 120, height = 120 },
				uvRect = { u0 = 0.0078125, v0 = 0.675781, u1 = 0.476562, v1 = 0.910156 },
				spriteSourceSize = { width = 120, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite3.png",
				spriteColorRect = { x = 0, y = 0, width = 120, height = 120 },
				uvRect = { u0 = 0.484375, v0 = 0.4375, u1 = 0.953125, v1 = 0.671875 },
				spriteSourceSize = { width = 120, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite4.png",
				spriteColorRect = { x = 0, y = 0, width = 120, height = 120 },
				uvRect = { u0 = 0.0078125, v0 = 0.4375, u1 = 0.476562, v1 = 0.671875 },
				spriteSourceSize = { width = 120, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

