-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:078248ff2ed788fe6002606ff7ce6dd9$
-- 

return {
	texture = 'main.png',
	frames = {
			{
				name = "open_seconds_scene.png",
				spriteColorRect = { x = 0, y = 0, width = 212, height = 52 },
				uvRect = { u0 = 0.015625, v0 = 0.0078125, u1 = 0.421875, v1 = 0.835938 },
				spriteSourceSize = { width = 212, height = 52 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "sprite1.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.4375, v0 = 0.734375, u1 = 0.90625, v1 = 0.96875 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite2.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.4375, v0 = 0.492188, u1 = 0.90625, v1 = 0.726562 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite3.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.4375, v0 = 0.25, u1 = 0.90625, v1 = 0.484375 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite4.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.4375, v0 = 0.0078125, u1 = 0.90625, v1 = 0.242188 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

