-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:918a62c52db2dbb6cfa2a0904fc781f6$
-- 

return {
	texture = 'second.png',
	frames = {
			{
				name = "forest1.png",
				spriteColorRect = { x = 0, y = 0, width = 122, height = 77 },
				uvRect = { u0 = 0.0078125, v0 = 0.441406, u1 = 0.484375, v1 = 0.591797 },
				spriteSourceSize = { width = 122, height = 77 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "forest2.png",
				spriteColorRect = { x = 0, y = 0, width = 157, height = 78 },
				uvRect = { u0 = 0.0078125, v0 = 0.285156, u1 = 0.621094, v1 = 0.4375 },
				spriteSourceSize = { width = 157, height = 78 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hello.png",
				spriteColorRect = { x = 0, y = 0, width = 139, height = 57 },
				uvRect = { u0 = 0.703125, v0 = 0.175781, u1 = 0.925781, v1 = 0.447266 },
				spriteSourceSize = { width = 139, height = 57 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "line1.png",
				spriteColorRect = { x = 0, y = 0, width = 173, height = 13 },
				uvRect = { u0 = 0.941406, v0 = 0.00390625, u1 = 0.992188, v1 = 0.341797 },
				spriteSourceSize = { width = 173, height = 13 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "line2.png",
				spriteColorRect = { x = 0, y = 0, width = 192, height = 19 },
				uvRect = { u0 = 0.0078125, v0 = 0.134766, u1 = 0.757812, v1 = 0.171875 },
				spriteSourceSize = { width = 192, height = 19 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "return_to_main_scene.png",
				spriteColorRect = { x = 0, y = 0, width = 237, height = 65 },
				uvRect = { u0 = 0.0078125, v0 = 0.00390625, u1 = 0.933594, v1 = 0.130859 },
				spriteSourceSize = { width = 237, height = 65 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sun.png",
				spriteColorRect = { x = 0, y = 0, width = 65, height = 72 },
				uvRect = { u0 = 0.492188, v0 = 0.451172, u1 = 0.773438, v1 = 0.578125 },
				spriteSourceSize = { width = 65, height = 72 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "world.png",
				spriteColorRect = { x = 0, y = 0, width = 176, height = 54 },
				uvRect = { u0 = 0.0078125, v0 = 0.175781, u1 = 0.695312, v1 = 0.28125 },
				spriteSourceSize = { width = 176, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

