return {
    ["layout_type"] = "scalable",
    ["layout_width"] = 427.0,
    ["layout_height"] = 320.0,
    ["layout_h_align"] = "center",
    ["props"] = {
        {
            ["align_bottom"] = true,
            ["name"] = "sun.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 273,
            ["x"] = 41,
            ["type"] = "sprite",
            ["id"] = 1,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "forest1.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 98,
            ["x"] = 313,
            ["type"] = "sprite",
            ["id"] = 2,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "line1.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 60,
            ["x"] = 315,
            ["type"] = "sprite",
            ["id"] = 3,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "line2.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 47,
            ["x"] = 113,
            ["type"] = "sprite",
            ["id"] = 4,
        },
        {
            ["align_bottom"] = false,
            ["name"] = "forest2.png",
            ["align_left"] = false,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 233,
            ["x"] = 325,
            ["type"] = "sprite",
            ["id"] = 5,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "hello.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 238,
            ["x"] = 190,
            ["type"] = "sprite",
            ["id"] = 6,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "world.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 177,
            ["x"] = 262,
            ["type"] = "sprite",
            ["id"] = 7,
        }
    }
}