-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:992abcd58afb12daaac0eeb3bb782958$
-- 

return {
	texture = 'main-part2.png',
	frames = {
			{
				name = "220px-Lenna-2.png",
				spriteColorRect = { x = 0, y = 0, width = 220, height = 220 },
				uvRect = { u0 = 0.0078125, v0 = 0.0078125, u1 = 0.867188, v1 = 0.867188 },
				spriteSourceSize = { width = 220, height = 220 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

