-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:5afd85084f444032afba79b44bf85d74$
-- 

return {
	texture = 'main.png',
	frames = {
			{
				name = "hello_world.png",
				spriteColorRect = { x = 0, y = 0, width = 121, height = 30 },
				uvRect = { u0 = 0.015625, v0 = 0.015625, u1 = 0.960938, v1 = 0.25 },
				spriteSourceSize = { width = 121, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite1.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.265625, v0 = 0.515625, u1 = 0.5, v1 = 0.75 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite2.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.265625, v0 = 0.265625, u1 = 0.5, v1 = 0.5 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite3.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.015625, v0 = 0.515625, u1 = 0.25, v1 = 0.75 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite4.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 30 },
				uvRect = { u0 = 0.015625, v0 = 0.265625, u1 = 0.25, v1 = 0.5 },
				spriteSourceSize = { width = 30, height = 30 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

