-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:978442d56c82b884646dc54a38da9fec$
-- 

return {
	texture = 'main-hd.png',
	frames = {
			{
				name = "hello_world.png",
				spriteColorRect = { x = 0, y = 0, width = 242, height = 60 },
				uvRect = { u0 = 0.015625, v0 = 0.0078125, u1 = 0.484375, v1 = 0.953125 },
				spriteSourceSize = { width = 242, height = 60 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "sprite1.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.5, v0 = 0.734375, u1 = 0.96875, v1 = 0.96875 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite2.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.5, v0 = 0.492188, u1 = 0.96875, v1 = 0.726562 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite3.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.5, v0 = 0.25, u1 = 0.96875, v1 = 0.484375 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite4.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0.5, v0 = 0.0078125, u1 = 0.96875, v1 = 0.242188 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

