return {
    {
        ["align_bottom"] = false,
        ["name"] = "sprite1.png",
        ["align_left"] = true,
        ["y_unit"] = "px",
        ["x_unit"] = "px",
        ["y"] = 48,
        ["x"] = 51,
        ["type"] = "sprite",
        ["id"] = 1,
    },
    {
        ["align_bottom"] = true,
        ["name"] = "sprite3.png",
        ["align_left"] = true,
        ["y_unit"] = "px",
        ["x_unit"] = "px",
        ["y"] = 52,
        ["x"] = 50,
        ["type"] = "sprite",
        ["id"] = 2,
    },
    {
        ["align_bottom"] = false,
        ["name"] = "sprite2.png",
        ["align_left"] = false,
        ["y_unit"] = "px",
        ["x_unit"] = "px",
        ["y"] = 50,
        ["x"] = 55,
        ["type"] = "sprite",
        ["id"] = 3,
    },
    {
        ["align_bottom"] = true,
        ["name"] = "sprite4.png",
        ["align_left"] = false,
        ["y_unit"] = "px",
        ["x_unit"] = "px",
        ["y"] = 53,
        ["x"] = 52,
        ["type"] = "sprite",
        ["id"] = 4,
    },
    {
        ["align_bottom"] = true,
        ["name"] = "hello_world.png",
        ["align_left"] = true,
        ["y_unit"] = "%",
        ["x_unit"] = "%",
        ["y"] = 50,
        ["x"] = 50.0,
        ["type"] = "sprite",
        ["id"] = 5,
    }
}