return {
    ["layout_type"] = "scalable",
    ["layout_width"] = 427.0,
    ["layout_height"] = 320.0,
    ["layout_h_align"] = "center",
    ["props"] = {
        {
            ["align_bottom"] = false,
            ["name"] = "sprite1.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 28,
            ["x"] = 29,
            ["type"] = "sprite",
            ["id"] = 1,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "sprite1.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 30,
            ["x"] = 30,
            ["type"] = "sprite",
            ["id"] = 2,
        },
        {
            ["align_bottom"] = false,
            ["name"] = "sprite1.png",
            ["align_left"] = false,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 27,
            ["x"] = 27,
            ["type"] = "sprite",
            ["id"] = 3,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "sprite1.png",
            ["align_left"] = false,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 27,
            ["x"] = 30,
            ["type"] = "sprite",
            ["id"] = 4,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "hello_world.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 276,
            ["x"] = 208,
            ["type"] = "sprite",
            ["id"] = 5,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "hello_world.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 229,
            ["x"] = 210,
            ["type"] = "sprite",
            ["id"] = 6,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "hello_world.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 182,
            ["x"] = 212,
            ["type"] = "sprite",
            ["id"] = 7,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "hello_world.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 137,
            ["x"] = 213,
            ["type"] = "sprite",
            ["id"] = 8,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "hello_world.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 88,
            ["x"] = 206,
            ["type"] = "sprite",
            ["id"] = 9,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "hello_world.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 42,
            ["x"] = 205,
            ["type"] = "sprite",
            ["id"] = 10,
        }
    }
}