return {
    ["props"] = {
        {
            ["align_bottom"] = false,
            ["name"] = "sprite1.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 22,
            ["x"] = 22,
            ["type"] = "sprite",
            ["id"] = 1,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "sprite3.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 25,
            ["x"] = 23,
            ["type"] = "sprite",
            ["id"] = 2,
        },
        {
            ["align_bottom"] = false,
            ["name"] = "sprite2.png",
            ["align_left"] = false,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 23,
            ["x"] = 28,
            ["type"] = "sprite",
            ["id"] = 3,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "sprite4.png",
            ["align_left"] = false,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 24,
            ["x"] = 30,
            ["type"] = "sprite",
            ["id"] = 4,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "hello_world.png",
            ["align_left"] = true,
            ["y_unit"] = "%",
            ["x_unit"] = "%",
            ["y"] = 50.0,
            ["x"] = 50.0,
            ["type"] = "sprite",
            ["id"] = 5,
        },
        {
            ["align_bottom"] = false,
            ["name"] = "sprite1.png",
            ["align_left"] = true,
            ["y_unit"] = "%",
            ["x_unit"] = "px",
            ["y"] = 40,
            ["x"] = 61,
            ["type"] = "sprite",
            ["id"] = 6,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "sprite3.png",
            ["align_left"] = true,
            ["y_unit"] = "%",
            ["x_unit"] = "px",
            ["y"] = 45,
            ["x"] = 62,
            ["type"] = "sprite",
            ["id"] = 7,
        },
        {
            ["align_bottom"] = false,
            ["name"] = "sprite2.png",
            ["align_left"] = false,
            ["y_unit"] = "%",
            ["x_unit"] = "px",
            ["y"] = 41,
            ["x"] = 54,
            ["type"] = "sprite",
            ["id"] = 8,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "sprite4.png",
            ["align_left"] = false,
            ["y_unit"] = "%",
            ["x_unit"] = "px",
            ["y"] = 45,
            ["x"] = 54,
            ["type"] = "sprite",
            ["id"] = 9,
        },
        {
            ["align_bottom"] = false,
            ["name"] = "sprite1.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "%",
            ["y"] = 25,
            ["x"] = 46,
            ["type"] = "sprite",
            ["id"] = 10,
        },
        {
            ["align_bottom"] = false,
            ["name"] = "sprite2.png",
            ["align_left"] = false,
            ["y_unit"] = "px",
            ["x_unit"] = "%",
            ["y"] = 24,
            ["x"] = 45,
            ["type"] = "sprite",
            ["id"] = 11,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "sprite3.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "%",
            ["y"] = 28,
            ["x"] = 45,
            ["type"] = "sprite",
            ["id"] = 12,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "sprite4.png",
            ["align_left"] = false,
            ["y_unit"] = "px",
            ["x_unit"] = "%",
            ["y"] = 29,
            ["x"] = 46,
            ["type"] = "sprite",
            ["id"] = 13,
        }
    }
}