-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:ce46417d58c1bafd707b793db6454b62$
-- 

return {
	texture = 'main.png',
	frames = {
			{
				name = "forest1.png",
				spriteColorRect = { x = 0, y = 0, width = 586, height = 373 },
				uvRect = { u0 = 0.00195312, v0 = 0.487305, u1 = 0.574219, v1 = 0.669434 },
				spriteSourceSize = { width = 586, height = 373 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "forest2.png",
				spriteColorRect = { x = 0, y = 0, width = 749, height = 371 },
				uvRect = { u0 = 0.00195312, v0 = 0.171387, u1 = 0.733398, v1 = 0.352539 },
				spriteSourceSize = { width = 749, height = 371 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hello.png",
				spriteColorRect = { x = 0, y = 0, width = 668, height = 272 },
				uvRect = { u0 = 0.00195312, v0 = 0.353516, u1 = 0.654297, v1 = 0.486328 },
				spriteSourceSize = { width = 668, height = 272 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "line1.png",
				spriteColorRect = { x = 0, y = 0, width = 832, height = 60 },
				uvRect = { u0 = 0.901367, v0 = 0.000976562, u1 = 0.959961, v1 = 0.407227 },
				spriteSourceSize = { width = 832, height = 60 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "line2.png",
				spriteColorRect = { x = 0, y = 0, width = 919, height = 89 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.899414, v1 = 0.0444336 },
				spriteSourceSize = { width = 919, height = 89 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sun.png",
				spriteColorRect = { x = 0, y = 0, width = 305, height = 343 },
				uvRect = { u0 = 0.65625, v0 = 0.408203, u1 = 0.991211, v1 = 0.557129 },
				spriteSourceSize = { width = 305, height = 343 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "world.png",
				spriteColorRect = { x = 0, y = 0, width = 841, height = 256 },
				uvRect = { u0 = 0.00195312, v0 = 0.0454102, u1 = 0.823242, v1 = 0.17041 },
				spriteSourceSize = { width = 841, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

