-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:f8a6c99d4e1a32ff2d76b36df74f2c16$
-- 

return {
	texture = 'main.png',
	frames = {
			{
				name = "forest1.png",
				spriteColorRect = { x = 14, y = 19, width = 587, height = 373 },
				uvRect = { u0 = 0.00195312, v0 = 0.487793, u1 = 0.575195, v1 = 0.669922 },
				spriteSourceSize = { width = 663, height = 405 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "forest2.png",
				spriteColorRect = { x = 21, y = 12, width = 750, height = 371 },
				uvRect = { u0 = 0.00195312, v0 = 0.171875, u1 = 0.734375, v1 = 0.353027 },
				spriteSourceSize = { width = 792, height = 441 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hello.png",
				spriteColorRect = { x = 22, y = 43, width = 669, height = 272 },
				uvRect = { u0 = 0.00195312, v0 = 0.354004, u1 = 0.655273, v1 = 0.486816 },
				spriteSourceSize = { width = 711, height = 342 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "line1.png",
				spriteColorRect = { x = 2, y = 27, width = 833, height = 60 },
				uvRect = { u0 = 0.901367, v0 = 0.000976562, u1 = 0.959961, v1 = 0.407715 },
				spriteSourceSize = { width = 855, height = 126 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "line2.png",
				spriteColorRect = { x = 17, y = 30, width = 919, height = 89 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.899414, v1 = 0.0444336 },
				spriteSourceSize = { width = 957, height = 153 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "sun.png",
				spriteColorRect = { x = 27, y = 30, width = 306, height = 343 },
				uvRect = { u0 = 0.657227, v0 = 0.408691, u1 = 0.992188, v1 = 0.558105 },
				spriteSourceSize = { width = 354, height = 381 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "world.png",
				spriteColorRect = { x = 26, y = 6, width = 841, height = 257 },
				uvRect = { u0 = 0.00195312, v0 = 0.0454102, u1 = 0.823242, v1 = 0.170898 },
				spriteSourceSize = { width = 897, height = 285 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

