-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:29b00303d65735ed3a21d24054080f26$
-- 

return {
	texture = 'main.png',
	frames = {
			{
				name = "forest1.png",
				spriteColorRect = { x = 3, y = 3, width = 122, height = 78 },
				uvRect = { u0 = 0.0078125, v0 = 0.320312, u1 = 0.484375, v1 = 0.625 },
				spriteSourceSize = { width = 138, height = 84 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "forest2.png",
				spriteColorRect = { x = 4, y = 2, width = 157, height = 78 },
				uvRect = { u0 = 0.0078125, v0 = 0.0078125, u1 = 0.621094, v1 = 0.3125 },
				spriteSourceSize = { width = 165, height = 92 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hello.png",
				spriteColorRect = { x = 4, y = 9, width = 140, height = 57 },
				uvRect = { u0 = 0.0078125, v0 = 0.769531, u1 = 0.554688, v1 = 0.992188 },
				spriteSourceSize = { width = 148, height = 71 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "line1.png",
				spriteColorRect = { x = 0, y = 4, width = 174, height = 14 },
				uvRect = { u0 = 0.9375, v0 = 0.0078125, u1 = 0.992188, v1 = 0.6875 },
				spriteSourceSize = { width = 178, height = 26 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "line2.png",
				spriteColorRect = { x = 2, y = 5, width = 193, height = 20 },
				uvRect = { u0 = 0.851562, v0 = 0.0078125, u1 = 0.929688, v1 = 0.761719 },
				spriteSourceSize = { width = 199, height = 32 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "sun.png",
				spriteColorRect = { x = 4, y = 5, width = 66, height = 73 },
				uvRect = { u0 = 0.5625, v0 = 0.707031, u1 = 0.820312, v1 = 0.992188 },
				spriteSourceSize = { width = 74, height = 79 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "world.png",
				spriteColorRect = { x = 4, y = 0, width = 177, height = 55 },
				uvRect = { u0 = 0.628906, v0 = 0.0078125, u1 = 0.84375, v1 = 0.699219 },
				spriteSourceSize = { width = 187, height = 59 },
				spriteTrimmed = true,
				textureRotated = true
			},
		}
	}

