return {
    ["layout_type"] = "elastic",
    ["props"] = {
        {
            ["align_bottom"] = true,
            ["name"] = "open_seconds_scene.png",
            ["align_left"] = true,
            ["y_unit"] = "%",
            ["x_unit"] = "%",
            ["y"] = 50,
            ["x"] = 50,
            ["type"] = "sprite",
            ["id"] = 1,
            ["uid"] = "open_second_scene",
        },
        {
            ["align_bottom"] = false,
            ["name"] = "sprite1.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 44,
            ["x"] = 40,
            ["type"] = "sprite",
            ["id"] = 2,
        },
        {
            ["align_bottom"] = false,
            ["name"] = "sprite2.png",
            ["align_left"] = false,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 41,
            ["x"] = 41,
            ["type"] = "sprite",
            ["id"] = 3,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "sprite3.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 40,
            ["x"] = 37,
            ["type"] = "sprite",
            ["id"] = 4,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "sprite4.png",
            ["align_left"] = false,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 41,
            ["x"] = 39,
            ["type"] = "sprite",
            ["id"] = 5,
        }
    }
}