-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:75cffcbc705c666e2fbafda10fe14784$
-- 

return {
	texture = 'main.png',
	frames = {
			{
				name = "hello_world.png",
				spriteColorRect = { x = 0, y = 0, width = 484, height = 120 },
				uvRect = { u0 = 0.0078125, v0 = 0.00390625, u1 = 0.476562, v1 = 0.949219 },
				spriteSourceSize = { width = 484, height = 120 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "sprite1.png",
				spriteColorRect = { x = 0, y = 0, width = 120, height = 120 },
				uvRect = { u0 = 0.484375, v0 = 0.71875, u1 = 0.953125, v1 = 0.953125 },
				spriteSourceSize = { width = 120, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite2.png",
				spriteColorRect = { x = 0, y = 0, width = 120, height = 120 },
				uvRect = { u0 = 0.484375, v0 = 0.480469, u1 = 0.953125, v1 = 0.714844 },
				spriteSourceSize = { width = 120, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite3.png",
				spriteColorRect = { x = 0, y = 0, width = 120, height = 120 },
				uvRect = { u0 = 0.484375, v0 = 0.242188, u1 = 0.953125, v1 = 0.476562 },
				spriteSourceSize = { width = 120, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite4.png",
				spriteColorRect = { x = 0, y = 0, width = 120, height = 120 },
				uvRect = { u0 = 0.484375, v0 = 0.00390625, u1 = 0.953125, v1 = 0.238281 },
				spriteSourceSize = { width = 120, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

