return {
    ["layout_type"] = "elastic",
    ["props"] = {
        {
            ["align_bottom"] = true,
            ["name"] = "hello_world.png",
            ["align_left"] = true,
            ["y_unit"] = "%",
            ["x_unit"] = "%",
            ["y"] = 50.0,
            ["x"] = 50.0,
            ["type"] = "sprite",
            ["id"] = 1,
        },
        {
            ["align_bottom"] = false,
            ["name"] = "sprite1.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 28,
            ["x"] = 27,
            ["type"] = "sprite",
            ["id"] = 2,
        },
        {
            ["align_bottom"] = false,
            ["name"] = "sprite2.png",
            ["align_left"] = false,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 30,
            ["x"] = 28,
            ["type"] = "sprite",
            ["id"] = 3,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "sprite3.png",
            ["align_left"] = true,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 29,
            ["x"] = 27,
            ["type"] = "sprite",
            ["id"] = 4,
        },
        {
            ["align_bottom"] = true,
            ["name"] = "sprite4.png",
            ["align_left"] = false,
            ["y_unit"] = "px",
            ["x_unit"] = "px",
            ["y"] = 29,
            ["x"] = 30,
            ["type"] = "sprite",
            ["id"] = 5,
        }
    }
}