-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:fb008178b9a7d66ed37cd8449e674354$
-- 

return {
	texture = 'main.png',
	frames = {
			{
				name = "220px-Lenna.png",
				spriteColorRect = { x = 0, y = 0, width = 138, height = 138 },
				uvRect = { u0 = 0.0078125, v0 = 0.0078125, u1 = 0.546875, v1 = 0.546875 },
				spriteSourceSize = { width = 138, height = 138 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite1.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 75 },
				uvRect = { u0 = 0.609375, v0 = 0.308594, u1 = 0.902344, v1 = 0.601562 },
				spriteSourceSize = { width = 75, height = 75 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite2.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 75 },
				uvRect = { u0 = 0.609375, v0 = 0.0078125, u1 = 0.902344, v1 = 0.300781 },
				spriteSourceSize = { width = 75, height = 75 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite3.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 75 },
				uvRect = { u0 = 0.308594, v0 = 0.554688, u1 = 0.601562, v1 = 0.847656 },
				spriteSourceSize = { width = 75, height = 75 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sprite4.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 75 },
				uvRect = { u0 = 0.0078125, v0 = 0.554688, u1 = 0.300781, v1 = 0.847656 },
				spriteSourceSize = { width = 75, height = 75 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

